// <auto-generated />
using System;
using ConectArte.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConectArte.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConectArte.Models.Asistente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CentroCulturalId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CentroCulturalId");

                    b.ToTable("Asistentes");
                });

            modelBuilder.Entity("ConectArte.Models.AsistenteTaller", b =>
                {
                    b.Property<int>("AsistenteId")
                        .HasColumnType("int");

                    b.Property<int>("TallerId")
                        .HasColumnType("int");

                    b.Property<int?>("Calificacion")
                        .HasColumnType("int");

                    b.HasKey("AsistenteId", "TallerId");

                    b.HasIndex("TallerId");

                    b.ToTable("AsistenteTaller");
                });

            modelBuilder.Entity("ConectArte.Models.CentroCultural", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCoordinador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.Property<int>("TelefonoCoordinador")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CentrosCulturales");
                });

            modelBuilder.Entity("ConectArte.Models.Docente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("ConectArte.Models.Recurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recursos");
                });

            modelBuilder.Entity("ConectArte.Models.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapacidadMaxima")
                        .HasColumnType("int");

                    b.Property<int>("CentroCulturalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CentroCulturalId");

                    b.ToTable("Salas");
                });

            modelBuilder.Entity("ConectArte.Models.Taller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapacidadMaxima")
                        .HasColumnType("int");

                    b.Property<int>("DocenteId")
                        .HasColumnType("int");

                    b.Property<int>("DuracionHoras")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SalaId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocenteId");

                    b.HasIndex("SalaId");

                    b.ToTable("Talleres");
                });

            modelBuilder.Entity("RecursoSala", b =>
                {
                    b.Property<int>("RecursosId")
                        .HasColumnType("int");

                    b.Property<int>("SalasId")
                        .HasColumnType("int");

                    b.HasKey("RecursosId", "SalasId");

                    b.HasIndex("SalasId");

                    b.ToTable("RecursoSala");
                });

            modelBuilder.Entity("ConectArte.Models.Asistente", b =>
                {
                    b.HasOne("ConectArte.Models.CentroCultural", "CentroCulturalAsignado")
                        .WithMany("Asistentes")
                        .HasForeignKey("CentroCulturalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CentroCulturalAsignado");
                });

            modelBuilder.Entity("ConectArte.Models.AsistenteTaller", b =>
                {
                    b.HasOne("ConectArte.Models.Asistente", "AsistenteAsignado")
                        .WithMany("AsistentesTalleres")
                        .HasForeignKey("AsistenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConectArte.Models.Taller", "TallerAsignado")
                        .WithMany("AsistentesTalleres")
                        .HasForeignKey("TallerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AsistenteAsignado");

                    b.Navigation("TallerAsignado");
                });

            modelBuilder.Entity("ConectArte.Models.Sala", b =>
                {
                    b.HasOne("ConectArte.Models.CentroCultural", "CentroCulturalAsignado")
                        .WithMany("Salas")
                        .HasForeignKey("CentroCulturalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CentroCulturalAsignado");
                });

            modelBuilder.Entity("ConectArte.Models.Taller", b =>
                {
                    b.HasOne("ConectArte.Models.Docente", "DocenteAsignado")
                        .WithMany("Talleres")
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConectArte.Models.Sala", "SalaAsignada")
                        .WithMany("Talleres")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocenteAsignado");

                    b.Navigation("SalaAsignada");
                });

            modelBuilder.Entity("RecursoSala", b =>
                {
                    b.HasOne("ConectArte.Models.Recurso", null)
                        .WithMany()
                        .HasForeignKey("RecursosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConectArte.Models.Sala", null)
                        .WithMany()
                        .HasForeignKey("SalasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConectArte.Models.Asistente", b =>
                {
                    b.Navigation("AsistentesTalleres");
                });

            modelBuilder.Entity("ConectArte.Models.CentroCultural", b =>
                {
                    b.Navigation("Asistentes");

                    b.Navigation("Salas");
                });

            modelBuilder.Entity("ConectArte.Models.Docente", b =>
                {
                    b.Navigation("Talleres");
                });

            modelBuilder.Entity("ConectArte.Models.Sala", b =>
                {
                    b.Navigation("Talleres");
                });

            modelBuilder.Entity("ConectArte.Models.Taller", b =>
                {
                    b.Navigation("AsistentesTalleres");
                });
#pragma warning restore 612, 618
        }
    }
}
